from .achievements import AchievementsCrawler
from .harvest_nodes import HarvestNodesCrawler
from .bestiary import BestiaryCrawler
from .character_data import CharacterDataCrawler
from .chat_wheel import ChatWheelCrawler
from .emotes import EmotesCrawler
from .pet_personalities import PetPersonalitiesCrawler
from .placeable_static_meshes import PlaceableStaticMeshesCrawler
from .placeable_static_meshes_manmade import PlaceableStaticMeshesManmadeCrawler
from .placeable_static_meshes_natural import PlaceableStaticMeshesNaturalCrawler
from .player_upgrades import PlayerUpgradesCrawler
from .tools_weapons import ToolsWeaponsCrawler
from .items import ItemsCrawler
from .item_sets import ItemSetsCrawler
from .crafting_recipes import CraftingRecipesCrawler
from .status_effects import StatusEffectsCrawler
from .mutations import MutationsCrawler

from .base_crawler import BaseCrawler